### ISSUE TITLE
Where is distracting_wrapper?

### ISSUE THREAD

**Issue by gunnxx** [manantomar/agent-centric-representations#1]
Hello, in the `dmc.make` function, you have `distracting_wrapper` (as well as `fb_mtenv_dmc`) which is not in your codebase. Where can I get this?

Thank you for the time

**Comment by manantomar** [comment]
Hi, you can find these two in the vd4rl repo [here](https://github.com/conglu1997/v-d4rl/tree/main/envs). We omitted these to provide the simplest possible implementation. Hope this helps!

**Comment by gunnxx** [comment]
I am wondering how did you implement the distraction for `Hard-Exo(c)` (ie. Figure 1 of the paper). So, does it mean that you trained the agent using `Hard-Exo(c)` dataset but evaluate it on the original observation with distraction provided in vd4rl repo?

**Comment by manantomar** [comment]
Sorry about the delay in replying! Yes, all evaluations were on the standard set of distractions provided in the vd4rl repo. We created our own dataset for Hard-Exo (c), where one of the 9 agents corresponds to the controllable agent, and the rest are random agents, followed by downsampling this combined 3 x 3 rendering.
