### ISSUE TITLE
Motivation for using InfoNCE in InfoGating

### ISSUE THREAD

**Issue by gunnxx** [manantomar/agent-centric-representations#2]
Hi,

I am wondering what is the motivation behind using InfoNCE for InfoGating as opposed to vanilla multistep inverse dynamics predictor as in ACRO. Also, did you do comparison between InfoNCE and vanilla predictor?

Thanks for the time!

**Comment by manantomar** [comment]
Hi! Yes, we did try the vanilla and InfoNCE versions for the ACRO predictor and both seem to do fairly similarly when combined with InfoGating. The InfoNCE version might be more useful for more complex, real world domains, for the same reasons that [Implicit BC seems to perform better than vanilla BC here](https://arxiv.org/abs/2109.00137).
